### ISSUE TITLE
Running out of memory on ogbn-arxiv

### ISSUE THREAD

**Issue by ryandeng1** [qitianwu/SGFormer#8]
Hi,

I am currently trying to run the code in the script for ogbn-arxiv, but I am running out of memory. Right now, it attempts to do a matrix multiply between two tensors which are each 169k by 256, and it allocated 100GB of VRam to do so.

I am wondering what settings I need to change in the script to get it to run?

Specifically, https://github.com/qitianwu/SGFormer/blob/466ff764f46e95a7bd3cd2985be08e205008776b/large/ours.py#L152 is where the error occurs.

Am I supposed to use main-batch.py instead of main.py?

Thanks!

**Comment by qitianwu** [comment]
Thanks for letting us know about this issue. This is indeed a mistake in the original code that implements the quadratic attention. Now the bug has been fixed with the correct version of simple linear attention. The code should run smoothly on the large datasets without OOM (for arxiv, we use `main.py` and for other large datasets, we use `main-batch.py`)
